### ISSUE TITLE
Any flag option to only return the records?

### ISSUE THREAD

**Issue by litan1106** [tflanagan/php-quickbase#3]
Any flag option to only return the records data instead of the whole reponses?

`{
    "action": "API_DoQuery",
    "errcode": 0,
    "errtext": "No error",
    "qid": -1,
    "qname": "",
    "table": {
        ...
        "records": [{
            "update_id": 1440699430305,
            "rid": 4336,
            "38": 4193,
        },  {
            "update_id": 1440699430383,
            "rid": 4775,
            "38": 4640,
        }]
    }
}`

**Comment by tflanagan** [comment]
Hey @litan1106,

As it stands, there isn't, but I'll look at a PR.

The flags are all derived from what QuickBase provides and uses. I've just taken the liberty to have default values for them. As far as I know, there is no flag to make it so QuickBase doesn't return their API boilerplate response.

The closest they have to this for API_DoQuery's is the [`fmt`](https://www.quickbase.com/api-guide/index.html#do_query.html#Request_Parameters) flag.

**Comment by litan1106** [comment]
Thanks. The Quickbase API returns too much junk along with records in the API_DoQuery's.
