### ISSUE TITLE
Why fid #3 (record id) isn't return with the API_GetRecordInfo?

### ISSUE THREAD

**Issue by litan1106** [tflanagan/php-quickbase#5]
Why fid #3 isn't return with the API_GetRecordInfo?

When I get a record from the Quickbase using the api API_GetRecordInfo, I don't see the fid #3. (record id)

**Comment by tflanagan** [comment]
Hey @litan1106,

I've added the API call to the test routine in b4035be and the [tests](https://travis-ci.org/tflanagan/php-quickbase/builds/133446200) are all returning positive

[QuickBase's documentation](https://www.quickbase.com/api-guide/index.html#getrecordinfo.html#Sample_Response) and [my documentation](https://github.com/tflanagan/node-quickbase/blob/master/documentation/api.md#api_getrecordinfo)

What exactly are you expecting and not seeing?

**Comment by litan1106** [comment]
Sorry, my mistake. I was trying to use mapFieldKeysToRecords function on the API_GetRecordInfo response field array. I guess it won't work because the array structure of the API_DoQuery is different from the API_GetRecordInfo
