### ISSUE TITLE
Get user field with api "API_DoQuery"

### ISSUE THREAD

**Issue by litan1106** [tflanagan/php-quickbase#6]
I am getting weird response like 

user: "58650665.bs2c"

$qb->api('API_DoQuery'....

**Comment by tflanagan** [comment]
Hey @litan1106,

Correct, QuickBase returns the QuickBase User ID for User field types.

**Comment by litan1106** [comment]
@tflanagan 
With the [official php sdk](https://github.com/QuickbaseAdmirer/QuickBase-PHP-SDK), I get Quickbase User value like

   "value" => "johnd@gmail.com"
    "printable" => "Doe, John"

I used API_DoQuery with both library but getting different result.

**Comment by tflanagan** [comment]
@litan1106,

I don't believe you are using API_DoQuery with the other lib. API_DoQuery would never return "value" or "printable" in their results. Only an API_GetRecordInfo would

Edit: I may be wrong, please let me know if I am, but I'm most certain you were using API_GetRecordInfo. I'm going to close this issue.

**Comment by litan1106** [comment]
Thanks again
