### ISSUE TITLE
Having an issue with AddRecord

### ISSUE THREAD

**Issue by bcoderr22** [tflanagan/php-quickbase#8]
Getting this error: Fatal error: Uncaught QuickBaseError: [11] Could not parse XML input. Found a field tag without a name or fid attribute.

Using this code not sure what I am missing here. FID 16 is the only required field in the Table. Any help would be appreciated.

```
$qb->api('API_AddRecord', array(
            'dbid' => 'MYTABLEID',
        'ticket' => $results['ticket'],
        'appToken' => 'MYAPPTOKEN',
            'fields' => array(
                array(
            'fid' => '16',
            'value' => 'Testertfd'
        )

            )

        ));
```

**Comment by tflanagan** [comment]
hmm,

quick question, why are you doing this: `'ticket' => $resuts['ticket']`

the ticket is stored internally and added to each api call without you having to manually insert it. Same question for appToken too.

**Comment by bcoderr22** [comment]
I had them set in the initial call and copy pasted. You are right all the other calls worked correctly without them. Removed them from the call.

**Comment by tflanagan** [comment]
did that fix it this issue? or same error?

**Comment by bcoderr22** [comment]
same issue

**Comment by bcoderr22** [comment]
I tried to add to it. Still no joy. Same Error.

Fatal error: Uncaught QuickBaseError: [11] Could not parse XML input. Found a field tag without a name or fid attribute. at line 2 column 128 (which is byte 172) thrown in 

```
$qb->api('API_AddRecord', array(
            'dbid' => 'DBID',
            'fields' => array(
                array(
            'fid' => '16',
            'name' => 'project_name',
            'value' => 'Testertfd',
            'type' => 'text',
        )

            )

        ));
```

**Comment by tflanagan** [comment]
can you tell me what version of the lib and php version you are using?

**Comment by bcoderr22** [comment]
Php 5.4 
Downloaded the lib today.

**Comment by tflanagan** [comment]
Hmm, this is a tough one. I'm running tests locally and everything is working fine with php 5.4.

Let me add some debugging code for you

**Comment by tflanagan** [comment]
Ok, @bcoderr22,

Update to version 1.3.5, then try this and paste what is dumped:

```
$qb = new \QuickBase\QuickBase(array(
 // settings
));

$qb->debug = true;

$qb->api('API_AddRecord', array(
    'dbid' => 'DBID',
    'fields' => array(
        array(
            'fid' => 16,
            'value' => 'Testertfd'
        )
    )
));
```

**Comment by bcoderr22** [comment]
That fixed the issue right up! Now it is entering into the DB. I really appreciate your help!

**Comment by tflanagan** [comment]
I'm confused, this change does nothing but dump the XML being sent to QuickBase.

Anyway, glad you were able to fix it.
